list()
type([])
names=["Riya","Piya","Tina"]
len(names)
names[0]
names[2]
names[0]="Mark"
names
lottery_numbers=[1,4,1997,7]
lottery_numbers
sorted(lottery_numbers,reverse=True)
lottery_numbers
lottery_numbers.sort()
lottery_numbers
dir(list)
help(list.count)
lottery_numbers
lottery_numbers.append(9999)
lottery_numbers
lottery_numbers+[1,3]
lottery_numbers.insert(0,55)
lottery_numbers
1 in lottery_numbers